name: TTD Proofs — build & publish
on:
  push: { branches: [ main ] }
  workflow_dispatch: {}
permissions:
  contents: write

jobs:
  proofs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }

      - name: Debug repo
        run: |
          pwd
          ls -la
          echo "::group::find index.html"; find . -maxdepth 2 -name 'index.html' -print; echo "::endgroup::"

      - name: Generate proofs
        run: python scripts/generate_proofs.py

      - name: Show proofs
        run: |
          echo "::group::proofs"; ls -la proofs || true; echo "::endgroup::"
          echo "::group::HASHES"; cat proofs/HASHES.txt || true; echo "::endgroup::"

      - name: Upload proofs folder (artifact)
        uses: actions/upload-artifact@v4
        with:
          name: ttd_proofs_pack
          path: proofs/**

      - name: Pack ZIP for releases (Python zipper)
        run: |
          python - <<'PY'
          import zipfile, os
          z=zipfile.ZipFile('ttd_proofs_pack.zip','w', zipfile.ZIP_DEFLATED)
          for root,_,files in os.walk('proofs'):
            for f in files:
              p=os.path.join(root,f)
              z.write(p, arcname=os.path.relpath(p, 'proofs'))
          z.close()
          print("Wrote ttd_proofs_pack.zip")
          PY

      - name: Commit proofs to repo (proofs/)
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(proofs): update proofs pack"
          file_pattern: proofs/**

      - name: Release on tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ttd_proofs_pack.zip
